#%RAML 1.0 DataType

type: object
properties:
  app_environment:
    type: string
    example: dunami
    description: The application environment that generated the alert
    enum: ['appdev.dunami', 'app.dunami', 'appqa.dunami']
  alert_types:
    type: string[]
    example: ['post', 'volume', 'sentiment']
    description: The template alert types
  analysis_name:
    type: string
    description: The name of the analysis in which the alert was generated
    example: tlot
  analysis_id:
    type: number
    description: The id of the analysis in which the alert was generated
    example: 13504
  folder_name:
    type: string
    description: The name of the folder which contains the analysis alert
    example: KC Devs
  folder_id:
    type: number
    description: The ID of the folder which contains the analysis alert
    example: 1169
  stream_end_date:
    type: datetime
    description: Stream end date
    example: 2017-11-29T19:18:15.953Z
  stream_frequency:
    type: string
    description: The frequency of the stream
    example: daily
    enum: ['hourly', 'daily', 'weekly']
  new_post_count:
    type: number
    description: Integer value of new posts
    example: 234
  stream_period:
    type: string
    description: The period of the stream
    example: Three months
    enum: ['One week', 'One month', 'Three months', 'Six months', 'One year']
