#%RAML 1.0
title: Dunami Email Template Service
version: v1

types: # global type definitions that can be reused throughout this API
  TemplateImage: !include ./templateImage.raml
  TemplateAttachment: !include ./templateAttachment.raml
  RenderedTemplate: !include ./renderedTemplate.raml
  AlertTemplateData: !include ./alertTemplateData.raml

/render_template:
  /alerts:
    post:
      body:
        application/json:
          type: AlertTemplateData
      responses:
        200:
          body:
            application/json:
              type: RenderedTemplate

/download_attachment:
  /{file_id}:
    get:
      responses:
        200:
          body:
            image/png:
