#%RAML 1.0
title: Email Template Service
version: v1

types: # global type definitions that can be reused throughout this API
  TemplateAttachment: !include ./templateAttachment.raml
  Template: !include ./template.raml
  AlertTemplateRequest: !include ./alertTemplateRequest.raml

/render_template:
  /alerts:
    post:
      body:
        application/json:
          type: AlertTemplateRequest
      responses:
        200:
          body:
            application/json:
              type: Template

/download_attachment:
  /{file_id}:
    get:
      responses:
        200:
          body:
            image/png:
